# .github/workflows/selenium-tests.yml
name: Run Selenium Tests

# Define when the workflow should be triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Check out the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Install dependencies (Maven) and run the tests
      - name: Run Selenium Tests with Maven
        run: |
          mvn install
          mvn test
